# Ambianic base config
dynaconf_merge: true
default:
  data_dir: ./data

  logging:
    file: ./data/ambianic-log.txt
    level: INFO

  timeline:
    event_log: ./data/timeline-event-log.yaml

  notifications:
    providers: {}
    template:
      title: "[Ambianic.ai] ${event} recognized"
      body: >
        ${event} event has been recognized by the system.
        Visit https://ui.ambianic.ai/ for more details.
    labels:
      fall_detection: Fall
      object_detection: Object

  sources: {}

  ai_models:
    image_detection:
      model:
        tflite: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_coco_quant_postprocess.tflite
        edgetpu: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
      labels: /opt/ambianic-edge/ai_models/coco_labels.txt
    face_detection:
      model:
        tflite: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_face_quant_postprocess.tflite
        edgetpu: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite
      labels: /opt/ambianic-edge/ai_models/coco_labels.txt
      top_k: 2
    fall_detection:
      model:
        tflite: /opt/ambianic-edge/ai_models/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite
        edgetpu: /opt/ambianic-edge/ai_models/posenet_mobilenet_v1_075_721_1281_quant_decoder_edgetpu.tflite
      labels: /opt/ambianic-edge/ai_models/pose_labels.txt

  pipelines: {}
