name: Ambianic Edge CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_x86:
    # Skip build if the commit message includes the string '[skip ci]'
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Run build script
        env: 
          ARCH: "linux/amd64"
          TAG_SUFFIX: "amd64"
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          pwd
          ls -al
          echo GITHUB_WORKSPACE=${GITHUB_WORKSPACE}
          echo "ARCH=${ARCH}"
          echo "TAG_SUFFIX=${TAG_SUFFIX}"
          ${GITHUB_WORKSPACE}/build/ci-build-job.sh
  build_arm:
    # Skip build if the commit message includes the string '[skip ci]'
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Run build script
        env:
          ARCH: "linux/arm/v7"
          TAG_SUFFIX: "arm32v7"
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "ARCH=${ARCH}"
          ${GITHUB_WORKSPACE}/build/ci-build-job.sh
  release:
    needs: [build_x86, build_arm]
    if: github.event_name == 'push' && false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install npm
      run: |
        npm version
        npm ci
      env:
        CI: true
    - name: Semantic Release
      run: npx semantic-release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
