name: Container Security Scan
on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    # run once a week to check for any newly discovered vulnerabilities
    # that might have been sleeping in a published container image
    - cron: '35 0 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: anchore/scan-action@v2
      id: scan
      with:
        image: "ambianic/ambianic-edge:latest"
        acs-report-enable: true
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
